-- TaskManager Database Initialization
-- gvenzl/oracle-xe runs init scripts as SYS, so we connect as APP_USER

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TASKMANAGER;

CREATE SEQUENCE TASKMANAGER.TASKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE TASKMANAGER.TASKS (
    ID NUMBER(10) PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    STATUS NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DUE_DATE TIMESTAMP NULL,
    CONSTRAINT CHK_STATUS CHECK (STATUS IN (0, 1, 2))
);

GRANT ALL ON TASKMANAGER.TASKS TO TASKMANAGER;
GRANT SELECT ON TASKMANAGER.TASKS_SEQ TO TASKMANAGER;

INSERT INTO TASKMANAGER.TASKS (ID, TITLE, DESCRIPTION, STATUS, DUE_DATE) VALUES (TASKMANAGER.TASKS_SEQ.NEXTVAL, 'Sample Task 1', 'This is a sample task for testing', 0, CURRENT_TIMESTAMP + INTERVAL '7' DAY);
INSERT INTO TASKMANAGER.TASKS (ID, TITLE, DESCRIPTION, STATUS, DUE_DATE) VALUES (TASKMANAGER.TASKS_SEQ.NEXTVAL, 'Sample Task 2', 'Another sample task', 1, CURRENT_TIMESTAMP + INTERVAL '14' DAY);
INSERT INTO TASKMANAGER.TASKS (ID, TITLE, DESCRIPTION, STATUS, DUE_DATE) VALUES (TASKMANAGER.TASKS_SEQ.NEXTVAL, 'Completed Task', 'This task is done', 2, NULL);
COMMIT;
